apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
availabilityZones:
  - us-east-1a
  - us-east-1b
metadata:
  name: eks-otel-demo
  region: us-east-1
  version: "1.31"
  tags:
    karpenter.sh/discovery: eks-otel-demo
    created-by: eksctl
    env: eks-otel-demo
iam:
  withOIDC: true
vpc:
  cidr: 10.42.0.0/16
  clusterEndpoints:
    privateAccess: true
    publicAccess: true
remoteNetworkConfig:
  remoteNodeNetworks:
    - cidrs: ["10.52.0.0/16"]
  remotePodNetworks:
    - cidrs: ["10.53.0.0/16"]
addons:
  - name: vpc-cni
    version: 1.19.2
    configurationValues: '{"env":{"ENABLE_PREFIX_DELEGATION":"true", "ENABLE_POD_ENI":"true", "POD_SECURITY_GROUP_ENFORCING_MODE":"standard"},"enableNetworkPolicy": "true", "nodeAgent": {"enablePolicyEventLogs": "true"}}'
    resolveConflicts: overwrite
managedNodeGroups:
  - name: worker-nodes
    desiredCapacity: 2
    minSize: 1
    maxSize: 3
    instanceType: t2.xlarge
    privateNetworking: true
    releaseVersion: "1.31.3-20250103"
    updateConfig:
      maxUnavailablePercentage: 50
    labels:
      eksctl-default: "yes"